version: '3.8'

services:
  game1:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: 2048-container-1
    volumes:
      - game1-data:/app/data

  game2:
    build:
      context: .
    ports:
      - "8081:8080"
    container_name: 2048-container-2
    volumes:
      - game2-data:/app/data

volumes:
  game1-data:
  game2-data:
